lyceym/about/urls.py
from django.urls import path
from about import views

app_name = 'about'
urlpatterns = [
    path('about/', views.description, name='about'),
]

lyceym/catalog/urls.py
from django.urls import path, re_path
from catalog import views

app_name = 'catalog'
urlpatterns = [
    path('', views.item_list, name='catalog'),
    re_path(r'(?P<pk>^[1-9]\d*)/$', views.item_detail, name='catalog_item'),
]

lyceym/feedback/urls.py
from django.urls import path
from feedback import views

app_name = 'feedback'
urlpatterns = [
    path('', views.feedback, name='feedback'),
]

lyceym/homepage/urls.py
from django.urls import path
from homepage import views

app_name = 'homepage'
urlpatterns = [
    path('', views.home, name='homepage'),
]

lyceym/lyceym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('catalog/', include('catalog.urls')),
    path('', include('about.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('feedback', include('feedback.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

lyceym/templates/includes/footer.html
{% load static %}
   <footer class="py-3 my-4">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
         <li class="nav-item"><a href={% url "homepage:homepage"%} class="nav-link px-2 text-muted">Home</a></li>
         <li class="nav-item"><a href={% url "catalog:catalog"%} class="nav-link px-2 text-muted">Catalog</a></li>
         <li class="nav-item"><a href={% url "about:about"%} class="nav-link px-2 text-muted">About</a></li>
         <li class="nav-item"><a href={% url "feedback:feedback"%} class="nav-link px-2 text-muted">Feedback</a></li>
      </ul>
      <p class="text-center text-muted">&copy; 2022 Amogus SuS, Inc</p>
   </footer>

lyceym/templates/includes/header.html
{% load static %}
<header>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"></button>
         <img src="{% static "img/1.png" %}" alt="Если вы это читаете, то видимо что-то пошло не так" width="50" height="40" class='startimg'>
         {% if user.is_authenticated %}
            <a href='/auth/profile/' class='name'>Привет, {{ user.username }} </a>
         {% else %}
            <a href="/auth/login/" class='name'>Войти</a>
         {% endif %}

         {% if user.is_staff %}
            <a class="name_two" href='/auth/user_list/'>Список пользователей</a>
         {% endif %}
         <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
               <li class="nav-item">
                  {% with request.resolver_match.url_name as view_name %}
                  <a class="nav-link {% if view_name == "homepage" %} active {% endif %}" href={% url "homepage:homepage"%}>Главная</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link {% if view_name == "catalog" %} active {% endif %}" href={% url "catalog:catalog"%}>Каталог</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link {% if view_name == "about" %} active {% endif %}" href={% url "about:about"%}>О проекте</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link {% if view_name == "feedback" %} active {% endif %}" href={% url "feedback:feedback"%}>Связаться</a>
               </li>
                  {% endwith %}
               
            </ul>
         </div>
      </div>
   </nav>
</header>

lyceym/templates/includes/item.html
<table class="table">
    <thead>
      <tr>
        <th scope="col">Имя</th>
        <th scope="col">Категория</th>
        <th scope="col">Текст</th>
        <th scope="col">Тэги</th>
        <th scope="col">Превью</th>
      </tr>
    </thead>
    <tbody>
        {% for item in items %}
        <tr>
            <td><a class="name" href="/catalog/{{item.id}}">{{item.name}}</a></td>
            {% ifchanged %}
              <td><b>{{item.category}}</b></td>
            {% else %}
              <td>{{item.category}}</td>
            {% endifchanged %}
            <td>{{ item.text|striptags|truncatewords:10 }}</td>
            <td>
                {% for tag in item.tag.all %}
                    {{ tag }}
                {% endfor %}
            </td>
            <td>
              <img src="{{ item.photo.url }}" alt="Если вы это читаете, то видимо что-то пошло не так" class="catalogimg">
            </td>
        {% endfor %}
    </tbody>
  </table>
  